name: Scan-Pull-Request

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - 14.0
      - 13.0
      - qa-14
      - qa-13

jobs:
  build:
    name: Scan Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Make variable environment
        run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")"  >> $GITHUB_ENV
        shell: bash        
      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.HEAD_REF }}
      - name: Retrieve entire repository history
        run: |
          git fetch --prune --unshallow
      - name: Run scan of the PR
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.host.url=https://sonarqube.novobi.com/
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=$REPOSITORY_NAME
          -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
          -Dsonar.pullrequest.base=${{ github.BASE_REF }}
          -Dsonar.pullrequest.github.repository=${{ github.repository }}
          -Dsonar.qualitygate.wait=true
          -Dsonar.scm.provider=git
          -Dsonar.java.binaries=/tmp
      - name: Set up Python actions
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Set up Sonarqube users
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python ./.github/workflows/setup-sonar.py       
